name: r_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-tidyverse
  - r-rmarkdown
  - r-usethis
  - r-curl
  - r-bookdown
  - r-sidrar
  - r-ggplot2
  - r-dplyr
  - r-lubridate
  - r-knitr
  - r-kableExtra
  - r-DT
  - r-forcats
  - r-plotly
  - r-highcharter