---
title: "Projeto pessoal"
output: 
  bookdown::html_document2:
    theme: lumen
    split_by: "section"
    fig_width: 7
    fig_height: 6
    fig_caption: true
    number_sections: false 
    toc: yes
    toc_depth: 3
    toc_float:
        collapsed: no
        smooth_scroll: yes
    css: "style.css"
date: "Atualizado em `r paste0(format(Sys.Date(), format = '%d de '), c('janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro')[as.integer(format(Sys.Date(), format = '%m'))], format(Sys.Date(), format = ' de %Y'))`"
---
<!-- Inclua a biblioteca Font Awesome -->
<script src="https://kit.fontawesome.com/4e10600d5e.js" crossorigin="anonymous"></script>

<!-- Carregando fontes -->
<style>
  @@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap');
</style>

<!-- Configuração do corpo do site -->
<style>
  body {
    text-align: justify;
    line-height: 1.5;
    font-family: 'Nunito Sans', sans-serif;
    
  }

/* Estilos para telas menores que 600 pixels de largura */
@media only screen and (max-width: 600px) {
  body {
    margin-left: 0; /* Remove o recuo na margem esquerda para telas menores */
    font-size: 2rem;
  }

  .dataTables_wrapper .dataTables_length,
  .dataTables_wrapper .dataTables_filter,
  .dataTables_wrapper .dataTables_info,
  .dataTables_wrapper .dataTables_paginate {
    font-size: 0.8rem;
    font-family: 'Nunito Sans', sans-serif;
    color: #636363;
  
  }
}

/* Estilos específicos para os títulos e parágrafos no conteúdo do documento */
  h1 {
    color: #0066cc; /* Azul para títulos de nível 1 */
    font-size: 4rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  h2 {
    color: #3399ff; /* Azul claro para títulos de nível 2 */
    font-size: 2rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  h3 {
    color: #66b2ff; /* Azul ainda mais claro para títulos de nível 3 */
    font-size: 2rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  p {
    font-size: 2rem;
    font-family: 'Nunito Sans', sans-serif;
  }

</style>

<!-- Configuração dual-frames -->
<style>
  .dual-frames {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .frame {
    width: 48%;
    padding: 0.0rem;
    box-sizing: border-box;
    font-size: 1rem;
    margin-bottom: 0em;
  }
  
  .frame img {
    border: none; /* Remove a borda da imagem */
  }

  @media only screen and (max-width: 600px) {
    .dual-frames {
      flex-direction: column; /* Altera para layout vertical */
    }

    .frame {
      width: 100%; /* Ocupa toda a largura disponível */
    }
  }
</style>

<!-- distancia -->
<style>
  .distancia {
      margin-bottom: 5rem;
  }
</style>



```{r include=FALSE}
#carregando pacotes
library(bookdown)
library(sidrar)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
library(knitr)
library(kableExtra)
library(DT)
library(forcats)
library(plotly)
library(highcharter)
library(GetBCBData)

```

<!-- Começando o codigo -->

<div class="dual-frames">
<div class="frame">

Bem-vindo ao meu site!

<div class="spacer"></div>

Quero compartilhar com você este espaço dedicado à análise e visualização de dados econômicos e financeiros do Brasil e dos principais mercados globais.

<div class="spacer"></div>

Neste site, você encontrará tabelas e gráficos elaborados a partir de dados oficiais, os quais são extraídos com bibliotecas no R, como sidrar, GetBCBData e ipeadatar.

<div class="spacer"></div>

Para mais informações, você pode me encontrar no <a href="https://www.linkedin.com/in/luiz-felipe-meier-cfp®-69a3b6a2"><i class="fab fa-linkedin"></i> LinkedIn</a> ou entrar em contato através do <a href="mailto:luizfelipe.meier@hotmail.com"><i class="fas fa-envelope-square"></i> e-mail</a>.

<div class="spacer"></div>

</div>
<div class="frame">



</div>
</div>

<!-- hiperlinks -->


































