# install.R
devtools::install.packages(c("rmarkdown", 
                   "usethis", 
                   "bookdown",
                   "sidrar",
                   "ggplot2",
                   "highcharter",
                   "plotly",
                   "kableExtra",
                   "DT",
                   "knitr",
                   "forcats",
                   "lubridate",
                   "GetBCBData",
                   "dplyr",
                   "tidyverse",
                   "GetBCBData",
                   "curl",
                   "rmarkdown"
                   ), lib=Sys.getenv("R_LIBS"))
