---
title: "DADOS ECONÔMICOS DOS DEMAIS PAÍSES"
output: 
  bookdown::html_document2:
    theme: readable
    split_by: "section"
    fig_width: 7
    fig_height: 6
    fig_caption: true
    number_sections: false 
    toc: yes
    toc_depth: 3
    toc_float:
        collapsed: no
        smooth_scroll: yes
date: "Atualizado em `r Sys.setlocale('LC_TIME', 'Portuguese_Brazil') ; format(Sys.time(), format = '%d de %B de %Y')`"
---
<!-- Inclua a biblioteca Font Awesome -->
<script src="https://kit.fontawesome.com/4e10600d5e.js" crossorigin="anonymous"></script>

<!-- Configuração do corpo do site -->
<style>
  body {
    text-align: justify;
    line-height: 1.5;
    background-color: #f4f4f4;
  }

/* Estilos para telas menores que 600 pixels de largura */
@media only screen and (max-width: 600px) {
  body {
    margin-left: 0; /* Remove o recuo na margem esquerda para telas menores */
  }
}

  h1 {
    color: #0066cc; /* Azul para títulos de nível 1 */
  }

  h2 {
    color: #3399ff; /* Azul claro para títulos de nível 2 */
  }

  h3 {
    color: #66b2ff; /* Azul ainda mais claro para títulos de nível 3 */
  }

  p {
    font-size: 16px; /* Tamanho da fonte para parágrafos */
    color: #333333; /* Cor padrão para texto */
  }

</style>

```

# INTERNACIONAL

## AMERICA

### Estados Unidos

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI

### Argentina

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI

## ASIA

### China

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI

### Índia

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI

### Japão

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI

## EUROPA

### Alemanha

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI

### Rússia

#### CPI

#### INTEREST RATE

#### PAYROLL

#### PMI



