---
title: "Investimentos"
output: 
  bookdown::html_document2:
    theme: lumen
    split_by: "section"
    fig_width: 7
    fig_height: 6
    fig_caption: true
    number_sections: false 
    toc: yes
    toc_depth: 3
    toc_float:
        collapsed: no
        smooth_scroll: yes
    css: "style.css"
date: "Atualizado em `r Sys.setlocale('LC_TIME', 'Portuguese_Brazil') ; format(Sys.time(), format = '%d de %B de %Y')`"
---
<!-- Inclua a biblioteca Font Awesome -->
<script src="https://kit.fontawesome.com/4e10600d5e.js" crossorigin="anonymous"></script>

<!-- Carregando fontes -->
<style>
  @@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap');
</style>

<!-- Configuração do corpo do site -->
<style>
  body {
    text-align: justify;
    line-height: 1.5;
    font-family: 'Nunito Sans', sans-serif;
    
  }

/* Estilos para telas menores que 600 pixels de largura */
@media only screen and (max-width: 600px) {
  body {
    margin-left: 0; /* Remove o recuo na margem esquerda para telas menores */
    font-size: 2rem;
  }

  .dataTables_wrapper .dataTables_length,
  .dataTables_wrapper .dataTables_filter,
  .dataTables_wrapper .dataTables_info,
  .dataTables_wrapper .dataTables_paginate {
    font-size: 0.8rem;
    font-family: 'Nunito Sans', sans-serif;
    color: #636363;
  
  }
}

/* Estilos específicos para os títulos e parágrafos no conteúdo do documento */
  h1 {
    color: #0066cc; /* Azul para títulos de nível 1 */
    font-size: 4rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  h2 {
    color: #3399ff; /* Azul claro para títulos de nível 2 */
    font-size: 2rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  h3 {
    color: #66b2ff; /* Azul ainda mais claro para títulos de nível 3 */
    font-size: 2rem;
    font-family: "Bebas Neue", sans-serif;
  }
  
  p {
    font-size: 2rem;
    font-family: 'Nunito Sans', sans-serif;
  }

</style>

<!-- Configuração dual-frames -->
<style>
  .dual-frames {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .frame {
    width: 48%;
    border: 0.2rem solid #ddd;
    padding: 0.8rem;
    box-sizing: border-box;
    font-size: 1rem; /* Exemplo de tamanho de fonte para os quadros usando unidades relativas */

    /* Adicione uma margem inferior para espaçamento entre os quadros */
    margin-bottom: 1em;
  }

  /* Estilos para telas menores que 600 pixels de largura */
  @media only screen and (max-width: 600px) {
  body {
    margin-left: 0; /* Remove o recuo na margem esquerda para telas menores */
    font-size: 2rem;
    }
  }
</style>

```{r include=FALSE}
#carregando pacotes
library(bookdown)
library(sidrar)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
library(knitr)
library(kableExtra)
library(DT)
library(forcats)
library(plotly)
library(highcharter)
library(GetBCBData)

```

Site em construção..