name: Update Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install R
      run: |
        sudo apt-get update -y
        sudo apt-get install r-base
    
    - name: Install Pandoc and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc libcurl4-openssl-dev

    - name: Render R Markdown to HTML
      run: Rscript update_and_push.R

    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update site"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}