name: Update Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install R
      run: |
        sudo apt-get update -y
        sudo apt-get install r-base

    - name: Create Temporary Library Directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/tmp_library
        Rscript -e 'install.packages(c("rmarkdown", "usethis"), lib="$GITHUB_WORKSPACE/tmp_library")'

    - name: Render R Markdown to HTML
      run: Rscript update_and_push.R

    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update site"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}